# Generated by Django 2.0.8 on 2018-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslwebsite',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
