# Generated by Django 2.0.8 on 2018-09-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0002_auto_20180903_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslwebsite',
            old_name='url',
            new_name='domain',
        ),
    ]
